pre-push

diff --git a/.husky/pre-push b/.husky/pre-push
--- a/.husky/pre-push
+++ b/.husky/pre-push
@@ -1,23 +1,15 @@
 #!/usr/bin/env sh
 . "$(dirname -- "$0")/_/husky.sh"
 
-echo -e "===\n>> Pre-push Hook: Checking branch name"
+printf "\n>> Pre-push Hook: Checking branch name...\n"
 
-BRANCH=`git rev-parse --abbrev-ref HEAD`
-PROTECTED_BRANCHES="^(master|develop|staging)"
+BRANCH=$(git rev-parse --abbrev-ref HEAD)
 
-#echo -e "\n $BRANCH $PROTECTED_BRANCHES" && exit 1
-
-if [ $1 != *"$BRANCH"* ]
-then
-  echo -e "\n🚫 You must use (git push origin $BRANCH).\n" && exit 1
+if [ "$BRANCH" = "master" ]; then
+  printf "\nCannot push to remote master branch, please create your own branch and initiate a Merge Request.\n"
+  exit 1
 fi
 
-if [ "$BRANCH" =~ $PROTECTED_BRANCHES ]
-then
-  echo -e "\n🚫 Cannot push to remote $BRANCH branch, please create your own branch and initiate a Merge Request.\n" && exit 1
-fi
-
-echo -e ">> Finished checking branch name.\n==="
+printf "\n>> Finished checking branch name.\n"
 
 exit 0
